### ISSUE TITLE
Streamdeck plugin for Mac

### ISSUE THREAD

**Issue by dickmann** [oddbear/Revelator.io24.Api#1]
Hi oddbear, thanks for your kind offer, would be great if you could do a Mac Version too! Thank you!!!! Best regards, Michael

**Comment by oddbear** [comment]
I have never made a StreamDeck plugin for mac, so this is the first test.
Since I don't have the Revelator io24 connected to a mac, I cannot test that the plugin is loading and running correctly from here.

I have added a mac-only build under https://github.com/oddbear/Revelator.io24.Api/releases/tag/v0.0.5-beta if you are able to test.

**Comment by oddbear** [comment]
If this does not work, can you try changing the line:
`"CodePath": "Revelator.io24.StreamDeck.exe",` to 
`"CodePath": "Revelator.io24.StreamDeck",`

In the `manifest.json` file found under `~/Library/Application Support/com.elgato.StreamDeck/Plugins/com.oddbear.revelator.io24.sdPlugin/`

Then restart the StreamDeck application.

(or I can create a new package to test)

**Comment by dickmann** [comment]
Hi, I edited the manifest.json as described. I see the plugins on my streamdeck. But pressing the icon gives me the "!" sign as feedback, so there seems to be a conflict... any idea what could be the reason? (I removed companion for testing)...
Thanks for your efforts! Any chance to include a "Volume control" for this plugin too?

Kind regards, Michael

**Comment by oddbear** [comment]
Could you uninstall the previous plugin and try out the new build `com.oddbear.revelator.io24_2.streamDeckPlugin` under the same preview/assets (almost same name as last but with a _2 in the name).

This one worked on my MacBook (a 2018 Intel one with Monterey), without any other modifications needed.

The issue I got was during the device discovery in the plugin.

**Comment by oddbear** [comment]
Volume control is implemented in both the Loupedeck and Touch Portal one, so that should be possible.

The only thing is that I am unsure of what's the best way to actually do it. I use the Loupedeck myself, and with the knobs it's more natural (and I use it all the time). Should it be like increase/decrease with x dB, or set to x dB, or maybe both?

**Comment by dickmann** [comment]
I deleted the folder in the Library folder as described above and installed version 2. This time Mac asked me to accept incoming traffic which I allowed, this is new and it's working. I had to restart streamdeck twice (in a first try the buttons were not available), but now I have the buttons on my streamdeck. The first button "Main" is working (which is muting my mic, so I am already happy, the other buttons are shown on streamdeck but if I press them nothing happens, neither the streamdeck button surface changes nor does the function work... but great progress, we are getting there :-)

and fyi, I am still using UniversalControl v1.13, this was the original version with four channels... are you on the latest firmware? Maybe this is the reason...

**Comment by dickmann** [comment]
ok, I upgraded to the latest revelator io24 Firmware, now the Main AND the Fat L button are working. I probably just have to rename Broadcast (as I use another name). I can jump from Mix 1 to Main with the "Main" button, but not back to Mix1 or Mix2 (probably also naming convention).... big thank you, you made it :-) 👍  what are your names for Mix 1 and Mix 2?

**Comment by oddbear** [comment]
Thanks. :)

Internally they have static names, so custom naming should not break anything.

The naming should be MixA and MixB on the StreamDeck (if I understand the question). Custom names set in the UC app can be possible, but is not implemented on anything else than presets in the plugin (if I remember correctly). But setting names / icons etc. right in the StreamDeck app should not break anything.

I will need to check out and test all of theese scenarios later today.

**Comment by dickmann** [comment]
Hi, I guess the names inside the revelator might be different, because PreSonus renamed them in the different Versions... My firmware 1.21 is using "Main", "Mix 1" and "Mix 2" for the mixes (including the space character). Is it the the same with your Revelator IO 24 version? I agree, you can probably change the names on the StreamDeck screen, but it looks StreamDeck is not finding the right name conventions inside the revelator IO 24...?

**Comment by oddbear** [comment]
What version of Universal Control are you on? (on windows it's something like 3.6.2.85277 at this point)

I will check out the binding later today, there was a issue with that on a earlier version so it might be something there, or that there is something different on the Mac version.

The internal structure for mute/assign left mic would be "line/ch1/assign_aux2", so the "display name" should not matter.

**Comment by dickmann** [comment]
I use the latest version: Universal Control 3.6.2.85277 macOS x64 (Built on Jan 19 2022)

**Comment by oddbear** [comment]
I just tested, and everything seems to work as expected here. 🤔
Maybe I misunderstood your issue?

Could you send a picture of the StreamDeck app of the button not working?

I have the exact same version of UC as you on Mac OS X also.

Outputs are:
Main
Stream Mix A
Stream Mix B

this is in both StreamDeck and in UC.

Input "Mix", is toggle on/off that selected output.

**Comment by dickmann** [comment]
Hi, sorry, issue was sitting in front of my screen. I misunderstood the concept, just recognized that you choose the Headphone source when you go Streamdeck - configure streamdeck... Everything working great, you did it :-)

Would it be possible to add a button to toggle the loudspeaker on/off button? The red one on front/bottom of the revelator below the volume button?

**Comment by oddbear** [comment]
That is good to hear, and great feedback. :)

I have already code for reading the monitor mute button state, but never tried to set it to a new value. I tried it now, and the device does not response. Sadly this means that this is not possible.

There is still the options to add some sort of hack to either manipulate the output Blend, or the Main Out dB level.
This hack might be used as a replacement but will not be the same, and probably just be confusing for most.

**Comment by dickmann** [comment]
But bringing the Main out to 0 would be great too!

**Comment by oddbear** [comment]
That should be possible, and is already implemented in the windows test application.

However, I will not be able to implement this until after easter for the StreamDeck.

If you create a new issue, as a feature requests I can look into it when I am back home.

Since the plugin is using the same protocol as the UC app, in theory everything that is possible to change in that app, is possible to change in a plugin (something needs additional calculations, that is a lot of extra work).
