### ISSUE TITLE
Revelator Update for Loupedeck 6.0

### ISSUE THREAD

**Issue by Zephyriums** [oddbear/Revelator.io24.Api#16]
Hello, Do you plan on updating your Revelator plugin for loupedeck v6.0? I used it pretty often on earlier verisons.

**Comment by oddbear** [comment]
Hi, I have updated and submitted a 6.0 version.
However, I don think it out yet. I will find the installer when I get home, and upload it here.

**Comment by Zephyriums** [comment]
Awesome, Thank you!

**Comment by oddbear** [comment]
Can you try this one? It's the one I sent to Louepdeck.
[RevelatorPlugin.zip](https://github.com/user-attachments/files/17368631/RevelatorPlugin.zip)

**Comment by Zephyriums** [comment]
It works! thank you so much!
